version: '3'
services:

  ###    ZOOKEEPER    ####
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: 
      zookeeper
    logging:
      driver: "none"

  ###    KAFKA    ####
  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - "zookeeper"
    ports:
      - "9092:9092"
    container_name: 
      kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "none"
    
 
    ### Kafka PRODUCER  ###
  producer:
    build: 
      context: ./Analytics/Kafka_Producer
    depends_on:
      - "kafka"
      - "zookeeper"
    volumes:
      - ./Analytics/Kafka_Producer/input/business_review2.json:/data/business_review2.json
    container_name: 
      producer
    logging:
      driver: "none"
    
 ###  media_stelle ###
  media_stelle:
    build: 
      context: ./Analytics/Stream/media_stelle
    depends_on:
      - "kafka"
      - "zookeeper"
    container_name: 
      media_stelle
    #logging:
      #driver: "none"
    
 
  ### javascript_consumer ###
  javascript_consumer:
    build:
      context: ./Visualization/javascript_consumer
    depends_on:
      - "kafka"
      - "zookeeper"
    ports:
      - "3001:3001"
    volumes:
      - ./Visualization/javascript_consumer/socket.io.js:/socket.io.js
    container_name: 
      javascript_consumer


 ### html_pages ###
  html_pages:
    build:
      context: ./Visualization/html_pages
    depends_on:
      - "javascript_consumer"
    container_name:
      html_pages
    ports:
      - "8081:80"
    environment:
      - NGINX_PORT=8081


    
 


